Update jansson dependency instructions for macOS (#398)
The latest tap does not have an optional `--with-jansson` option
anymore, it's installed by default since
[February 23 2021](https://github.com/universal-ctags/homebrew-universal-ctags/commit/82db2cf9cb0cdecf62ca9405e767ec025b5ba8ed)

Calling the install command with the `--with-jansson` option would
return an error from Homebrew.

```
Error: invalid option: --with-jansson
```

In time the whole macOS instructions can probably be removed, but since
the change was made recently, existing installs may need to reinstall
ctags before it works with the JSON feature.